version: '3'

networks:
  laravel:

services:
  site:
    restart: always
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
      - "7000-8000:7000-8000"
    volumes:
      - /var/www:/var/www:delegated
    depends_on:
      - php
      - php73
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    restart: always
    volumes:
      - /var/www:/var/www:delegated
    networks:
      - laravel

  php73:
    build:
      context: .
      dockerfile: php7.3.dockerfile
    container_name: php73
    restart: always
    volumes:
      - /var/www:/var/www:delegated
    networks:
      - laravel

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    container_name: composer
    volumes:
      - /var/www:/var/www
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    networks:
      - laravel
    entrypoint: ['composer', '--ignore-platform-reqs']

  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - /var/www:/var/www
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan
    volumes:
      - /var/www:/var/www:delegated
    working_dir: /var/www/html
    user: laravel
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel
